[kafka.config]
"group.id" = "elara-kv"
"bootstrap.servers" = "localhost:9092"
"enable.partition.eof" = "false"
"session.timeout.ms" = "6000"
"enable.auto.commit" = "true"

[ws]
addr = "localhost:9002"

[nodes.polkadot]
addr = "wss://rpc.polkadot.io"
