[kafka.config]
"group.id" = "elara-kv"
"bootstrap.servers" = "localhost:9092"
"enable.partition.eof" = "false"
"session.timeout.ms" = "6000"
"enable.auto.commit" = "true"

[kafka]
topics = ["polkadot", "kusama"]

[ws]
addr = "localhost:9002"

[nodes.polkadot1]
addr = "wss://rpc.polkadot.io"
