[package]
name = "elara-kv-component"
version = "0.1.0"
authors = ["yjhmelody <yjh465402634@gmail.com>"]
edition = "2018"

description = "Elara KV component for subscribing substrate node data"
keywords = ["kafka", "substrate", "websocket", "jsonrpc", "polkadot", "kusama"]
categories = ["web", "blockchain"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.1", features = ["full"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
log = "0.4"
env_logger = "0.8"
jsonrpc-pubsub = "17.0"
thiserror = "1.0"
once_cell = "1.5"
tokio-tungstenite = { version = "0.13", features = ["connect", "tls", "stream"]}
async-jsonrpc-client = { git = "https://github.com/koushiro/async-jsonrpc-client", branch = "master"}
jsonrpc-types = "^0.3.2"
structopt = "0.3"
async-trait = "0.1"
#tokio-stream = "0.1"

[[bin]]
name = "elara-kv"
path = "bin/main.rs"
