name: elara-kv

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: ${{ matrix.rust-version }}
      - run: cargo test --verbose
      - run: cargo test --doc
